iris:
  postgres:
    host: "localhost"
    port: 5432
    db_name: "iris"
    user: "iris"
    pass: "iris"
    ssl: false
  http:
    port: 9090
    admin_pass: "wcrFWjU3gVS1VFB4mF6CvzH1SYU3MZ"
  go:
    mode: "debug"
  notifications:
    smsir:
      api_key: ""
      line_number: ""
      enabled: true
      priority: 2
    kavenegar:
      api_token: ""
      sender: ""
      enabled: true
      priority: 1
    # Email configuration
    email:
      host: ""
      port: ""
      user: ""
      password: ""
      from: ""
      enabled: ""
  scheduler:
    scheduler_enabled: "true"
    mobile_scheduler:
      start_at: "1s"
      interval: "600s"
      workers: "1"
      queue_size: "1"
      cache_capacity: "1"
    # Alert Scheduler configuration
    alert_scheduler:
      start_at: "3s"
      interval: "10s"
      workers: "1"
      queue_size: "10"
    # Message Status
    message_status:
      start_at: "4s"
      interval: "20s"
      workers: "10"
      queue_size: "100"
  jwt_secret: ""
  signup_enabled: "false"